### ISSUE TITLE
Is it still on progress ?

### ISSUE THREAD

**Issue by Psycokwet** [0LEG0/next-yate#1]
Hello !

I'm interested to use yate, but I'm still figuring things out yet...
I found your package, is it abandonned ? :o

**Comment by 0LEG0** [comment]
the project is alive. Any constructive suggestions for its development are welcome.

**Comment by Psycokwet** [comment]
Hello !

It's good to know :) 

Unfortunately I'm a big noob on sip, telphony and so on, so I won't be able to help before long I guess... I'm not even sure that I can use Yate for what I want to do, especially at my level on telephony haha. 

Anyway, I wish you the best of success with your project, and I hope maybe one day I would be able to contribute to something like that :)
